#[package]
name = "mipt_Rust_Programming"
version = "0.1.0"
edition = "2023"

[workspace]
members = [
    # Problems
    "problems/tutorial/add",
    "problems/intro/combinations",
    "problems/intro/conway",
    "problems/intro/min-queue",
]
